### ISSUE TITLE
Why can't I achieve the accuracy in the paper using your code？

### ISSUE THREAD

**Issue by libaolong4473** [marmot-xy/CMBS#5]
I am using the same environment and parameters as you, with a GeForce RTX 3080TI GPU and existing VGG-like audio and VGG visual features. Why is the best accuracy for supervised tasks 78.184 and weakly supervised tasks 72.3. Is it because of my GPU ? We look forward to your reply,thank you.

**Comment by marmot-xy** [comment]
The AVE dataset has a relatively small amount of data, so testing on it may inevitably introduce some performance variance due to the random initialization of the model. You can try changing a few random seeds or adjusting the parameters, which might result in higher performance. Alternatively, you can directly use the checkpoint we provide for testing, which should achieve results similar to those reported in our paper.

**Comment by libaolong4473** [comment]
Thank you for your reply!
